baseURL = "https://rayprogramming.com/"
languageCode = "en-us"
title = "James Ray's Blog"
enableGitInfo = true
enableEmoji = true

[analytics]
enabled = true

[analytics.services.google]
id = "G-ZZ2207Q2P0"

# [permalinks]
# posts = "/:sections/:slug/:title"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
[languages]
[languages.en]
languageName = "English"
weight = 1

# Control TOC depth
[markup]
[markup.tableOfContents]
startLevel = 2
endLevel = 6
ordered = false
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = false
[outputs]
home = ["HTML","JSON"]

[params]
  background = "/images/IMG_2343.JPG"
  # GitHub repo URL of your site
  gitRepo = "https://github.com/rayprogramming/rayprogramming"

  # specify whether you want to write some blog posts or not
  enableBlogPost = true

  # specify whether you want to show Table of Contents in reading page
  enableTOC = true

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
[params.newsletter]
enable = true

[params.logo]
main = "/images/IMG_2007.JPG"
[params.features]
[params.features.comment]
enable = true
[params.features.comment.giscus]
repo = "rayprogramming/rayprogramming.com"
theme = "dark"

[params.features.portfolio]
enable = true
[params.features.blog]
enable = true
[params.features.notes]
enable = true

[frontmatter]
date = [":filename","date","publishDate","lastmod"]
lastmod = [":fileModTime",":git","lastmod","date","publishDate"]
publishDate = ["publishDate","date"]
expiryDate = "expiryDate"

[[module.imports]]
path = "github.com/hugo-toha/toha/v4"

[[module.mounts]]
source = "static/files"
target = "static/files"

[[module.mounts]]
source = "./node_modules/flag-icon-css/flags"
target = "static/flags"

[[module.mounts]]
source = "./node_modules/@fontsource/mulish/files"
target = "static/files"

[[module.mounts]]
source = "./node_modules/katex/dist/fonts"
target = "static/fonts"

[darkMode]
enable = true